from app import alchDB
from app.models import User, Blade, Driver, UserBladeLink

alchDB.create_all()

Pyra = Blade(name='Pyra', role='Dps', element='Fire', weapon='Unique', description='Story blade, unique weapon is Aegis Sword, can only be used by Rex as a driver')
Mythra = Blade(name='Mythra', role='Dps', element='Light', weapon='Unique', description='Story blade, unique weapon is Aegis Sword, can only be used by Rex as a driver')
Dromarch = Blade(name='Dromarch', role='Healer', element='Water', weapon='Twin Rings', description='Story blade, only usable by Nia as a driver')
Poppi = Blade(name='Poppi', role='Tank', element='Earth', weapon='Unique', description='Story blade, only usable by Tora as a driver, artificial blade, can be customised')
Brighid = Blade(name='Brighid', role='Tank', element='Fire', weapon='Unique', description='Story blade, only usable by Morag as a driver, Unique weapon is Whip Swords')
Pandoria = Blade(name='Pandoria', role='Dps', element='Electric', weapon='Unique', description='Story blade, only usable by Zeke as a driver, unique weapon is Big Bang Edge')
KosMos = Blade(name='Kos-Mos', role='Dps', element='Light', weapon='Ether Cannon', description='Rare blade obtainable through core crystals, can be used by any driver')
Boreas = Blade(name='Boreas', role='Healer', element='Wind', weapon='Bit-Ball', description='Rare blade obtainable through core crystals, can be used by any driver')
Dahlia = Blade(name='Dahlia', role='Healer', element='Ice', weapon='Bit-Ball', description='Rare blade obtainable through core crystals, can be used by any driver')
Zenobia = Blade(name='Zenobia', role='Dps', element='Wind', weapon='Great Axe', description='Rare blade, obtainable through core crystals, can be used by any driver, extremely good for challenging super bosses')
Agate = Blade(name='Agate', role='Dps', element='Earth', weapon='Great Axe', description='Rare blade, obtainable through core crystals, can be used by any driver')
Kasandra = Blade(name='Kasandra', role='Tank', element='Dark', weapon='Shield Hammer', description='Rare blade, obtainable through defeating unique monster, can be used by any driver')
Electra = Blade(name='Electra', role='Tank', element='Electric', weapon='Shield Hammer', description='Rare blade, obtainable through core crystals, can be used by any driver')
Herald = Blade(name='Herald', role='Dps', element='Electric', weapon='Ether Cannon', description='Rare blade obtained through a quest in tantal, can be used by any driver')
Kora = Blade(name='Kora', role='Healer', element='Electric', weapon='Knuckle Claws', description='Rare blade obtained through core crystals, can be used by any driver')
Ursula = Blade(name='Ursula', role='Healer', element='Ice', weapon='Knucle Claws', description='Rare blade obtained through core crystals, can be used by any driver')
Nim = Blade(name='Nim', role='Healer', element='Earth', weapon='Knucle Claws', description='Rare blade obtained through core crystals, can be used by any driver')
Perun = Blade(name='Perun', role='Dps', element='Ice', weapon='Mega Lance', description='Rare blade obtained through core crystals, can be used by any driver')
Praxis = Blade(name='Praxis', role='Dps', element='Water', weapon='Mega Lance', description='Rare blade obtained through side quest line, can be used by any driver')

Rex = Driver(name='Rex', description='Main playable character, avalible from the start, main blade is Pyra')
Nia = Driver(name='Nia', description='Nia is a driver that becomes avalible in chapter 2, she is primarily a healer based driver due to her main blade being Dromarch, a healer blade')
Zeke = Driver(name='Zeke', description='Morag is a driver that becomes avalible in chapter 4, she is primarily a tank based driver due to her story blade being Bridhid, a tank blade')
Morag = Driver(name='Morag', description='Tora is a special driver due to his inability to use normal blades. Because of this, he designed and built his own artificial blade; Poppi')
Tora = Driver(name='Tora', description='Zeke is the final driver that becomes avalible in chapter 7. Zeke is primarily a dps style driver with his main blade being Pandoria')

alchDB.session.add(Pyra)
alchDB.session.add(Mythra)
alchDB.session.add(Dromarch)
alchDB.session.add(Poppi)
alchDB.session.add(Brighid)
alchDB.session.add(Pandoria)
alchDB.session.add(KosMos)
alchDB.session.add(Boreas)
alchDB.session.add(Dahlia)
alchDB.session.add(Zenobia)
alchDB.session.add(Agate)
alchDB.session.add(Kasandra)
alchDB.session.add(Electra)
alchDB.session.add(Herald)
alchDB.session.add(Kora)
alchDB.session.add(Ursula)
alchDB.session.add(Nim)
alchDB.session.add(Perun)
alchDB.session.add(Praxis)
alchDB.session.add(Rex)
alchDB.session.add(Nia)
alchDB.session.add(Zeke)
alchDB.session.add(Morag)
alchDB.session.add(Tora)
